const MATCH_ROUTES = 'MATCH_ROUTES';
const GET_ROUTES = 'GET_ROUTES';
const GET_VIEW = 'GET_VIEW';
const SET_OPEN_MENU = 'SET_OPEN_MENU';
const SET_ACTIVE_CHILD = 'SET_ACTIVE_CHILD';

export {
    MATCH_ROUTES,
    GET_ROUTES,
    GET_VIEW,
    SET_OPEN_MENU,
    SET_ACTIVE_CHILD
}
